Repository BrownGrey/DiscordBot, pull requests merged in 2022-10, with the labels that each got.

#4 Added Settings
  Commands/Message/Information/help.js
  Commands/Message/Information/invite.js
  Commands/Message/Information/ping.js
  Commands/Message/Information/stats.js
  Commands/Message/Information/uptime.js
  Commands/Message/Settings/247.js
  Commands/Message/Settings/autoresume.js
  Commands/Message/Settings/config.js
  Commands/Message/Settings/dj.js
  Commands/Message/Settings/prefix.js
  Commands/Message/Settings/reset.js
  Commands/Message/Settings/setupmusic.js
  Commands/Slash/Information/Settings/247.js
  Commands/Slash/Information/Settings/dj.js
  Commands/Slash/Information/Settings/reset.js
  Commands/Slash/Information/Settings/setupmusic.js
  Commands/Slash/Information/help.js
  Commands/Slash/Information/invite.js
  Commands/Slash/Information/ping.js
  Commands/Slash/Information/stats.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#6 Added desription in readme
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Remove.js Structure
  Commands/Message/Music/replay.js
  Commands/Message/Music/resume.js
  Commands/Message/Music/search.js
  Commands/Message/Music/seek.js
  Commands/Message/Music/skip.js
  Commands/Message/Music/stop.js
  Commands/Message/Music/volume.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 Update Info In slashes
  Commands/Slash/Information/Information/help.js
  Commands/Slash/Information/Information/invite.js
  Commands/Slash/Information/Information/ping.js
  Commands/Slash/Information/Information/stats.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Created Loop
  Commands/Slash/Information/Music/filter.js
  Commands/Slash/Information/Music/jump.js
  Commands/Slash/Information/Music/loop.js
  Commands/Slash/Information/Music/move.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Queue Command Slash/Music #12
  Commands/Slash/Information/Music/playskip.js
  Commands/Slash/Information/Music/playtop.js
  Commands/Slash/Information/Music/queue.js
  Commands/Slash/Information/Music/remove.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Seek and skip
  Commands/Slash/Information/Music/seek.js
  Commands/Slash/Information/Music/skip.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Stop Command
  Commands/Slash/Information/Music/stop.js
  Commands/Slash/Information/Music/volume.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Website For the bot
  docs/web/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 CSS and Assets
  docs/web/assets/css/styles.css
  docs/web/assets/img/Wumpus.gif
  docs/web/assets/img/WumpusSmug.gif
  docs/web/assets/js/main.js
  docs/web/assets/js/scrollreveal.min.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 website src
  website/README.md
  website/docs/assets/images/favicon.png
  website/docs/assets/javascripts/bundle.76f349be.min.js
  website/docs/assets/javascripts/bundle.76f349be.min.js.map
  website/docs/assets/javascripts/lunr/min/lunr.ar.min.js
  website/docs/assets/javascripts/lunr/min/lunr.da.min.js
  website/docs/assets/javascripts/lunr/min/lunr.de.min.js
  website/docs/assets/javascripts/lunr/min/lunr.du.min.js
  website/docs/assets/javascripts/lunr/min/lunr.es.min.js
  website/docs/assets/javascripts/lunr/min/lunr.fi.min.js
  website/docs/assets/javascripts/lunr/min/lunr.fr.min.js
  website/docs/assets/javascripts/lunr/min/lunr.hu.min.js
  website/docs/assets/javascripts/lunr/min/lunr.it.min.js
  website/docs/assets/javascripts/lunr/min/lunr.ja.min.js
  website/docs/assets/javascripts/lunr/min/lunr.jp.min.js
  website/docs/assets/javascripts/lunr/min/lunr.multi.min.js
  website/docs/assets/javascripts/lunr/min/lunr.nl.min.js
  website/docs/assets/javascripts/lunr/min/lunr.no.min.js
  website/docs/assets/javascripts/lunr/min/lunr.pt.min.js
  website/docs/assets/javascripts/lunr/min/lunr.ro.min.js
  website/docs/assets/javascripts/lunr/min/lunr.ru.min.js
  website/docs/assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  website/docs/assets/javascripts/lunr/min/lunr.sv.min.js
  website/docs/assets/javascripts/lunr/min/lunr.tr.min.js
  website/docs/assets/javascripts/lunr/min/lunr.vi.min.js
  website/docs/assets/javascripts/lunr/tinyseg.js
  website/docs/assets/javascripts/workers/search.b0710199.min.js
  website/docs/assets/javascripts/workers/search.b0710199.min.js.map
  website/docs/assets/stylesheets/main.ca7ac06f.min.css
  website/docs/assets/stylesheets/main.ca7ac06f.min.css.map
  website/docs/assets/stylesheets/palette.f1a3b89f.min.css
  website/docs/assets/stylesheets/palette.f1a3b89f.min.css.map
  website/docs/index.html
  website/docs/installation/index.html
  website/docs/plugins/index.html
  website/docs/sitemap.xml
  website/docs/sitemap.xml.gz
  website/images/favicon.png
  website/index.html
  website/main.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Auth src
  src/auth/auth.js
  src/auth/passport.js
  src/bot.js
  src/commands/8-ball.js
  src/commands/ban.js
  src/commands/cat.js
  src/commands/clear.js
  src/commands/coin.js
  src/commands/dog.js
  src/commands/index.js
  src/commands/kick.js
  src/commands/ping.js
  src/commands/roll.js
  src/commands/serverinfo.js
  src/commands/stats.js
  src/commands/userinfo.js
  src/config/config.default.json
  src/config/settings.json
  src/config/theme.json
  src/config/version.json
  src/events/message.js
  src/events/ready.js
  src/index.js
  src/package-lock.json
  src/package.json
  src/public/home/assets/javascript/theme.js
  src/public/home/assets/javascript/theme.min.js
  src/public/home/assets/stylesheets/plugins.css
  src/public/home/assets/vendor/popper-js/umd/popper.min.js
  src/public/login/script.js
  src/public/login/style.css
  src/routes/guilds.js
  src/routes/home.js
  src/routes/login.js
  src/routes/plugins.js
  src/routes/settings.js
  src/routes/support.js
  src/themes/default.css
  src/views/error_pages/404.ejs
  src/views/home/guilds.ejs
  src/views/home/home.ejs
  src/views/home/plugins.ejs
  src/views/home/settings.ejs
  src/views/home/support.ejs
  src/views/login/login.ejs
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#22 Content src
  content/dashprev.JPG
  content/headerimage.png
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 commands json for web auth
  JSON/commands.json
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Legals
  PRIVACY_POLICY.md
  TERMS_OF_SERVICE.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 tokenLogin setup
  main.go
  message.json
  tokenLogin.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Fingerprints.json
  fingerprints.json
  go.mod
  go.sum
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 Utilities
  utilities/color.go
  utilities/encryption.go
  utilities/files.go
  utilities/misc.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 Instances
  instance/build.go
  instance/captcha.go
  instance/check_token.go
  instance/config.go
  instance/direct_messages.go
  instance/extra.go
  instance/headers.go
  instance/instance.go
  instance/protocol.go
  instance/scrape.go
  instance/token_util.go
  instance/types.go
  instance/websocket.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 Embed Assign
  button_click.go
  friend_spammer.go
  guild_leaver.go
  input/pfps/example_png.png
  invite_joiner.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 procfile
  Procfile
  yarn.lock
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 created index
  index.ts
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#40 ts message
  messages.ts
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 Create serverdb.rb
  serverdb.rb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#51 Swiper applicationcpp
  application.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#52 WSA and shard fix
  cluster.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#53 Warped Integration
  integration.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#59 cmdln control enhanced
  discord.sh
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
